services:
  - type: web
    name: coop-wordle
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

